In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


/kaggle/input/all-animes-in-mal/mal_anime.csv


In [2]:
anime=pd.read_csv("/kaggle/input/all-animes-in-mal/mal_anime.csv")

In [3]:
anime.head()

Unnamed: 0                                       title episodes  \
0           0            Fullmetal Alchemist: Brotherhood       64   
1           1                                 Steins;Gate       24   
2           2                   Bleach: Sennen Kessen-hen       13   
3           3                                    Gintama°       51   
4           4  Kaguya-sama wa Kokurasetai: Ultra Romantic       13   

            status     theme demographic                           genres  \
0  Finished Airing  Military     Shounen  Action,Adventure,Drama,Fantasy,   
1  Finished Airing   Unknown     Unknown           Drama,Sci-Fi,Suspense,   
2  Finished Airing   Unknown     Shounen        Action,Adventure,Fantasy,   
3  Finished Airing   Unknown     Shounen            Action,Comedy,Sci-Fi,   
4  Finished Airing    School      Seinen                  Comedy,Romance,   

  type favorites popularity rank  score    members  \
0   TV   218,277         #3   #1   9.10  3,190,961   
1   TV   183,596        #13   #2   9.07  2,452,142   
2   TV    18,421       #458   #3   9.06    455,428   
3   TV    16,042       #332   #4   9.06    599,235   
4   TV    29,397       #193   #5   9.05    832,346   

                                            synopsis  \
0  After a horrific alchemy experiment goes wrong...   
1  Eccentric scientist Rintarou Okabe has a never...   
2  Substitute Soul Reaper Ichigo Kurosaki spends ...   
3  Gintoki, Shinpachi, and Kagura return as the f...   
4  The elite members of Shuchiin Academy's studen...   

                          aired         duration    premiered  \
0    Apr 5, 2009 to Jul 4, 2010  24 min. per ep.  Spring 2009   
1   Apr 6, 2011 to Sep 14, 2011  24 min. per ep.  Spring 2011   
2  Oct 11, 2022 to Dec 27, 2022  24 min. per ep.    Fall 2022   
3   Apr 8, 2015 to Mar 30, 2016  24 min. per ep.  Spring 2015   
4   Apr 9, 2022 to Jun 25, 2022  23 min. per ep.  Spring 2022   

                 studios  
0                  Bones  
1              White Fox  
2                Pierrot  
3  Bandai Namco Pictures  
4           A-1 Pictures

In [4]:
anime.rename(columns={"Unnamed: 0": "index"}, inplace=True)

In [5]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24262 entries, 0 to 24261
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   index        24262 non-null  int64  
 1   title        24262 non-null  object 
 2   episodes     24262 non-null  object 
 3   status       24262 non-null  object 
 4   theme        24262 non-null  object 
 5   demographic  24262 non-null  object 
 6   genres       24262 non-null  object 
 7   type         24262 non-null  object 
 8   favorites    24262 non-null  object 
 9   popularity   24262 non-null  object 
 10  rank         20197 non-null  object 
 11  score        15294 non-null  float64
 12  members      24262 non-null  object 
 13  synopsis     24262 non-null  object 
 14  aired        24262 non-null  object 
 15  duration     24262 non-null  object 
 16  premiered    24262 non-null  object 
 17  studios      24262 non-null  object 
dtypes: float64(1), int64(1), object(16)
memory usa

In [6]:
!pip install summarytools
from summarytools import dfSummary
dfSummary(anime)

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for summarytools: filename=summarytools-0.2.3-py3-none-any.whl size=8577 sha256=fcedfd7a3350be65b2bbe6c4a767f660f4beba06c4641d1f4e593c66a0f1e833
  Stored in directory: /root/.cache/pip/wheels/d5/8a/5d/008e2127a7f9dd64d066f16e5ea268fa52823dc929c982d6f1
Successfully built summarytools


In [7]:
features=['genres','theme','demographic','synopsis','type']
print(features)

['genres', 'theme', 'demographic', 'synopsis', 'type']


In [8]:
for ani in features:
    anime[ani]=anime[ani].fillna('')
   

In [9]:
combined_features=anime['genres']+' '+anime['theme']+' '+anime['demographic']+' '+anime['synopsis']+' '+anime['type']
print(combined_features)

0        Action,Adventure,Drama,Fantasy, Military Shoun...
1        Drama,Sci-Fi,Suspense, Unknown Unknown Eccentr...
2        Action,Adventure,Fantasy, Unknown Shounen Subs...
3        Action,Comedy,Sci-Fi, Unknown Shounen Gintoki,...
4        Comedy,Romance, School Seinen The elite member...
                               ...                        
24257    Hentai, Unknown Unknown In which the act of ra...
24258    Hentai, Unknown Unknown Based off the eroge by...
24259    Hentai, Unknown Unknown Sister Rosaria is work...
24260    Hentai, Unknown Unknown There are nine men and...
24261    Drama,Romance,Hentai, Unknown Unknown Yusuke's...
Length: 24262, dtype: object


In [10]:
vectorizer=TfidfVectorizer()

In [11]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [12]:
similarity=cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.07976103 0.07649965 ... 0.06869925 0.03861332 0.04281262]
 [0.07976103 1.         0.09168122 ... 0.10087775 0.03525027 0.09895145]
 [0.07649965 0.09168122 1.         ... 0.05723554 0.01816791 0.06337459]
 ...
 [0.06869925 0.10087775 0.05723554 ... 1.         0.06631765 0.07055901]
 [0.03861332 0.03525027 0.01816791 ... 0.06631765 1.         0.048456  ]
 [0.04281262 0.09895145 0.06337459 ... 0.07055901 0.048456   1.        ]]


In [13]:
anime_name=input("enter anime name: ")
list_of_all_titles = anime['title'].tolist()

find_close_match = difflib.get_close_matches(anime_name, list_of_all_titles)
print(find_close_match)
close_match = find_close_match[0]

index_of_the_anime = anime[anime.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_anime]))

sorted_similar_anime = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print('anime suggested for you : \n')

i = 1

for anim in sorted_similar_anime:
    index = anim[0]
    title_from_index = anime[anime.index==index]['title'].values[0]
    if (i<30):
        print(i, '.',title_from_index)
        i+=1

enter anime name:  one piece


['One Piece', 'One Piece 4D', 'Ange Vierge']
anime suggested for you : 

1 . One Piece
2 . One Piece: Episode of East Blue - Luffy to 4-nin no Nakama no Daibouken
3 . One Piece Movie 14: Stampede
4 . One Piece Film: Z
5 . One Piece: Romance Dawn Story
6 . One Piece Film: Strong World Episode 0
7 . One Piece Film: Strong World
8 . One Piece: Oounabara ni Hirake! Dekkai Dekkai Chichi no Yume!
9 . Kaizoku Ouji
10 . One Piece 3D2Y: Ace no shi wo Koete! Luffy Nakama Tono Chikai
11 . Mashou no Nie 3
12 . Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare
13 . Shironeko Project: Zero Chronicle
14 . One Piece Film: Red
15 . One Piece Movie 08: Episode of Alabasta - Sabaku no Oujo to Kaizoku-tachi
16 . One Piece Movie 01
17 . Helck
18 . One Piece Movie 04: Dead End no Bouken
19 . Rennyo to Sono Haha
20 . Shen Mu
21 . Doraemon Movie 19: Nobita no Nankai Daibouken
22 . Tokyo One Piece Tower: Tongari Shima no Dai Hihou
23 . One Piece: Episode of Sabo - 3 Kyoudai no Kizuna Kiseki no Saikai to Uk